import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import { defineConfig, loadEnv } from 'vite';

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, '.', '');
  return {
    plugins: [react(), tailwindcss()],
    define: {
      'process.env.GEMINI_API_KEY': JSON.stringify(env.GEMINI_API_KEY),
    },
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
      },
    },
    build: {
      rollupOptions: {
        output: {
          // ─── Widget vs SPA chunking trade-off ───────────────────────────
          // Historically `manualChunks: undefined` + `cssCodeSplit: false`
          // forced a single bundle so external clients (Garnier) could inject
          // the widget via one <script> tag.
          //
          // Phase 3.A — package.json only exposes `vite build` (no widget-
          // specific build script). The current SPA entry was 550 KB gz which
          // is unacceptable for the chat-only landing. We re-enable vendor
          // splitting for the SPA build. React/ReactFlow/TipTap/Supabase land
          // in their own long-cache chunks and the entry shrinks ~55%.
          //
          // TODO Phase 4 — split into two configs (widget = single-file via
          // build.lib.entry; SPA = current chunked output). Until then the
          // single-file widget path is generated by a future dedicated
          // command, NOT by `npm run build`.
          // Function form — match by node_modules path so we don't choke on
          // peer-dep packages (e.g. `@tiptap/pm`) that lack a root entry.
          // Order matters: specific vendors first, then generic prefixes.
          manualChunks(id) {
            if (!id.includes('node_modules')) return undefined;
            if (
              id.includes('node_modules/react/') ||
              id.includes('node_modules/react-dom/') ||
              id.includes('node_modules/scheduler/')
            ) {
              return 'react-vendor';
            }
            if (
              id.includes('node_modules/@xyflow/') ||
              id.includes('node_modules/dagre/') ||
              id.includes('node_modules/@dagrejs/')
            ) {
              return 'reactflow-vendor';
            }
            if (
              id.includes('node_modules/@tiptap/') ||
              id.includes('node_modules/prosemirror-')
            ) {
              return 'tiptap-vendor';
            }
            if (id.includes('node_modules/@supabase/')) {
              return 'supabase-vendor';
            }
            if (
              id.includes('node_modules/react-markdown/') ||
              id.includes('node_modules/remark-') ||
              id.includes('node_modules/micromark') ||
              id.includes('node_modules/mdast-')
            ) {
              return 'markdown-vendor';
            }
            return undefined;
          },
          entryFileNames: 'assets/[name].js',
          assetFileNames: 'assets/[name].[ext]',
        },
      },
      // CSS still inlined into JS — keeps the no-CSS-file invariant the widget
      // path relies on. Re-evaluate when Phase 4 splits the configs.
      cssCodeSplit: false,
    },
    server: {
      // HMR is disabled in AI Studio via DISABLE_HMR env var.
      // Do not modifyâ€"file watching is disabled to prevent flickering during agent edits.
      hmr: process.env.DISABLE_HMR !== 'true',
      proxy: {
        '/graph': {
          target: process.env.SWARM_API_URL || 'http://localhost:8000',
          changeOrigin: true,
          secure: false,
        },
        '/swarm': {
          target: process.env.SWARM_API_URL || 'http://localhost:8000',
          changeOrigin: true,
          secure: false,
          timeout: 300000, // 5 min for debate calls
        },
        '/api': {
          target: 'http://localhost:3001',
          changeOrigin: true,
        },
      },
    },
  };
});
